#!/usr/bin/env bash

## Install ansible
sudo apt install -y curl python3 python-is-python3 python3-distutils
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python get-pip.py
sudo python -m pip install ansible