- hosts: localhost
  tasks:
    - name: Installing System Packages 1
      become: true
      apt:
        name: ["build-essential"]
    - name: Installing System Packages 2
      become: true
      apt:
        name: ["i3","curl","git","vim","rofi","htop","neofetch","pavucontrol","nvidia-settings","flameshot","kitty","keepassxc","qemu","virt-manager","fzf","ripgrep","fd"]
    - name: Installing System Packages 3
      become: true
      apt:
        name: ["cheese"]
    - name: Installing stow
      become: true
      apt: name=stow
    - name: Stow dotfiles
      shell: cd $HOME/dotfiles && stow home
    - name: Install snaps
      become: true
      snap:
        name: ["discord","spotify","keepassxc","code"]
        classic: yes
    - name: Make dev directory
      shell: mkdir ~/dev
