- hosts: localhost
  tasks:
    - name: Installing System Packages 1
      become: true
      apt:
        name: ["build-essential"]
    - name: Installing System Packages 2
      become: true
      apt:
        name: ["i3","curl","git","vim","zsh","rofi","htop","neofetch","pavucontrol","nvidia-settings","flameshot","kitty","keepassxc","qemu","virt-manager","fzf","ripgrep","fd-find"]
    - name: Installing System Packages 3
      become: true
      apt:
        name: ["cheese"]
    - name: Installing stow
      become: true
      apt: name=stow
    - name: Stow dotfiles
      shell: cd $HOME/dotfiles && stow home
    - name: Install snaps
      become: true
      snap:
        name: ["discord","spotify","keepassxc","code"]
        classic: yes
    - name: Make dev directory
      shell: "[ -d ~/dev ] || mkdir ~/dev"
    - name: Change shell to zsh
      shell: chsh -s $(which zsh) 
    - name: Check oh-my-zsh installed
      stat:
        path: /home/ricardo/.oh-my-zsh
      register: oh_my_stats
    - name: Oh-My-Zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
      when: oh_my_stats.stat.exists == False
      become_user: ricardo

