#!/usr/bin/env bash

rm -rf ~/.tmux.conf
ln -s $(pwd)/essentials/.tmux.conf ~/.tmux.conf
rm -rf ~/.aliases
ln -s $(pwd)/essentials/.aliases ~/.aliases
rm -rf ~/.vimrc
ln -s $(pwd)/essentials/.vimrc ~/.vimrc
rm -rf ~/.zshrc
ln -s $(pwd)/essentials/.zshrc ~/.zshrc
rm -rf ~/.config/awesome/rc.lua
ln -s $(pwd)/essentials/.config/awesome/rc.lua ~/.config/awesome/rc.lua
rm -rf ~/.config/i3/config
ln -s $(pwd)/essentials/.config/i3/config ~/.config/i3/config
rm -rf ~/.local/bin/tmux-sessionizer
ln -s $(pwd)/essentials/.local/bin/tmux-sessionizer ~/.local/bin/tmux-sessionizer
